### ISSUE TITLE
FileNotFoundError when processing sequence

### ISSUE THREAD

**Issue by anibali** [anibali/h36m-fetch#32]
```
!!! Error processing sequence, skipping: ('S1', '16', '1', '55011271')
Traceback (most recent call last):
  File ".\process_all.py", line 150, in process_subaction
    annots = process_view(out_dir, subject, action, subaction, camera)
  File ".\process_all.py", line 117, in process_view
    path.join(tmp_dir, 'img_%06d.jpg')
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл

!!! Error processing sequence, skipping: ('S1', '16', '1', '58860488')
Traceback (most recent call last):
  File ".\process_all.py", line 150, in process_subaction
    annots = process_view(out_dir, subject, action, subaction, camera)
  File ".\process_all.py", line 117, in process_view
    path.join(tmp_dir, 'img_%06d.jpg')
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл

!!! Error processing sequence, skipping: ('S1', '16', '1', '60457274')
Traceback (most recent call last):
  File ".\process_all.py", line 150, in process_subaction
    annots = process_view(out_dir, subject, action, subaction, camera)
  File ".\process_all.py", line 117, in process_view
    path.join(tmp_dir, 'img_%06d.jpg')
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\DELL\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

I am getting the above error message when I run **process_all.py**. I am pretty sure that I have extracted all the files correctly. @anibali could you please suggest a solution? Thanks.

_Originally posted by @yerzhan7orazayev in https://github.com/anibali/h36m-fetch/issues/22#issuecomment-720646073_

**Comment by anibali** [comment]
@yerzhan7orazayev Please ensure that your overall directory structure looks like this:

```
.
├── ...
├── extracted
│   ├── S1
│   ├── S11
│   ├── S5
│   ├── S6
│   ├── S7
│   ├── S8
│   └── S9
├── ...
├── process_all.py
├── ...
```

And each extracted subject should have the following layout:

```
extracted/S1
├── Poses_D2_Positions
│   ├── Directions 1.54138969.cdf
│   ├── Directions 1.55011271.cdf
│   ├── Directions 1.58860488.cdf
│   ├── Directions 1.60457274.cdf
│   ├── ...
├── Poses_D3_Positions
│   ├── Directions 1.cdf
│   ├── ...
├── Poses_D3_Positions_mono
│   ├── Directions 1.54138969.cdf
│   ├── Directions 1.55011271.cdf
│   ├── Directions 1.58860488.cdf
│   ├── Directions 1.60457274.cdf
│   ├── ...
├── Poses_D3_Positions_mono_universal
│   ├── Directions 1.54138969.cdf
│   ├── Directions 1.55011271.cdf
│   ├── Directions 1.58860488.cdf
│   ├── Directions 1.60457274.cdf
│   ├── ...
└── Videos
    ├── Directions 1.54138969.mp4
    ├── Directions 1.55011271.mp4
    ├── Directions 1.58860488.mp4
    ├── Directions 1.60457274.mp4
    ├── ...
```

**Comment by anibali** [comment]
@yerzhan7orazayev It is also possible that ffmpeg is encountering some kind of error. I have updated my code to show error output from ffmpeg (https://github.com/anibali/h36m-fetch/commit/99a723f5fbd2a5f00766385b84ad157871005d5f). Please pull the latest version of h36m-fetch before running `process_all.py` again.
