### ISSUE TITLE
Error processing sequence

### ISSUE THREAD

**Issue by HOH980820** [anibali/h36m-fetch#52]
!!! Error processing sequence, skipping: ('S5', '15', '2', '58860488')
 27%|###########3                              | 57/210 [00:08<00:22,  6.79it/s]
                                                                                
Traceback (most recent call last):
  File "/home/disk_share/hoh/data/learnable-triangulation/data/h36m-fetch/process_all.py", line 144, in process_subaction
    annots = process_view(out_dir, subject, action, subaction, camera)
  File "/home/disk_share/hoh/data/learnable-triangulation/data/h36m-fetch/process_all.py", line 106, in process_view
    call([
  File "/home/hoh/disk/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/hoh/disk/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/hoh/disk/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

 27%|###########3                              | 57/210 [00:08<00:22,  6.79it/s]
                                                                                
!!! Error processing sequence, skipping: ('S5', '15', '2', '60457274')
 27%|###########3                              | 57/210 [00:08<00:22,  6.79it/s]
                                                                                
Traceback (most recent call last):
  File "/home/disk_share/hoh/data/learnable-triangulation/data/h36m-fetch/process_all.py", line 144, in process_subaction
    annots = process_view(out_dir, subject, action, subaction, camera)
  File "/home/disk_share/hoh/data/learnable-triangulation/data/h36m-fetch/process_all.py", line 106, in process_view
    call([
  File "/home/hoh/disk/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/hoh/disk/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/hoh/disk/anaconda3/envs/torch/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Processing can be performed here, but in the end, only the corresponding folder in the process has no results**

**Comment by anibali** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

You need to install ffmpeg: `conda install -c conda-forge ffmpeg=3.2.4`

**Comment by HOH980820** [comment]
![image](https://user-images.githubusercontent.com/28781249/135067139-4d47ea9a-b9d5-4fd5-ab2d-63414b3b412e.png)
![image](https://user-images.githubusercontent.com/28781249/135067408-88400b74-7bc0-4587-a8d5-6a7c97888df5.png)
Excuse me, sir, I need help! I allow process in this place_ There is a problem with all.py. Cut the pictures that are not cropped out in the corresponding folder (S11)

**Comment by anibali** [comment]
The original issue has been resolved. The new issue has been moved to https://github.com/anibali/h36m-fetch/issues/53.
