### ISSUE TITLE
TypeError: float() argument must be a string or a number, not '_NoValueType'

### ISSUE THREAD

**Issue by limengyi-98** [anibali/h36m-fetch#55]
Traceback (most recent call last):
 97%|#########6| 29/30 [00:18<00:00,  1.53it/s]
  File "D:/limengyi/learning/motioNet/h36m-fetch/process_all.py", line 146, in process_subaction
                                               
    annots = process_view(out_dir, subject, action, subaction, camera)
 97%|#########6| 29/30 [00:18<00:00,  1.53it/s]
  File "D:/limengyi/learning/motioNet/h36m-fetch/process_all.py", line 90, in process_view
 75%|#######5  | 3/4 [00:00<00:00, 10.09it/s]
    frame_indices = select_frame_indices_to_include(subject, poses_3d_univ)
                                                 File "D:/limengyi/learning/motioNet/h36m-fetch/process_all.py", line 49, in select_frame_indices_to_include
    max_move = ((joints3d - prev_joints3d) ** 2).sum(axis=-1).max()
  File "D:\anaconda\envs\python36\lib\site-packages\numpy\core\_methods.py", line 47, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
TypeError: float() argument must be a string or a number, not '_NoValueType'

**Comment by anibali** [comment]
This is not a problem that I've encountered before. From a little bit of web searching, it seems like the people tend to encounter this when their Python environment is a bit broken.

**Comment by DanBmh** [comment]
With the provided docker container the processing worked correctly for me (tried it yesterday)

**Comment by limengyi-98** [comment]
Thanks very much,this problem was resolved after reloading pycharm.
