### ISSUE TITLE
fail to run download_all.py

### ISSUE THREAD

**Issue by XiumeiChen** [anibali/h36m-fetch#8]
Hello,
I installed python3, axel, and CDF, then I ran <python download_all.py>. However, I got the following error.
![image](https://user-images.githubusercontent.com/44281274/48415622-d92d6700-e788-11e8-9177-b456ccfd5f44.png)
Traceback (most recent call last):
  File "download_all.py", line 99, in <module>
    download_all(phpsessid)
  File "download_all.py", line 93, in download_all
    download_file(BASE_URL + '?' + query, out_file, phpsessid)
  File "download_all.py", line 38, in download_file
    url])
  File "/home/user1/anaconda3/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/user1/anaconda3/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/home/user1/anaconda3/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'axel'

**Comment by anibali** [comment]
It looks like axel is not installed correctly, since Python cannot find it on your path. Are you able to run `axel -V` from the command line?

**Comment by XiumeiChen** [comment]
@anibali Thanks.
Now I intalled axel correctly, but I have question with intall CDF. I ran "sudo apt-get install CDF", but I failed. What's CDF? How can I  install it?

**Comment by guofuzheng** [comment]
@XiumeiChen Hello, i created an account on Human3.6, but Human3.6 have not confirmed  my request. May i share your dataset with you? Thank you.
